name: simple_library
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.2+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.3
  flutter_spinkit: ^4.1.2
  font_awesome_flutter: ^8.10.0
  get_it: ^4.0.2
  dio: ^3.0.9
  provider: ^4.1.3
  get: ^3.25.6
  percent_indicator: "^2.1.5"
  expansion_tile_card: ^1.0.3
  flutter_rating_bar: ^3.0.1+1
  flutter_datetime_picker: ^1.5.0
  loading_overlay: ^0.2.1
  beautifulsoup: ^0.0.1
  transparent_image: ^1.0.0
  shared_preferences: ^0.5.8
  validators: ^2.0.1
  permission_handler: ^5.0.1+1
  fluttertoast: ^7.0.2
  image_picker: ^0.6.7+4
  image_cropper: ^1.3.0
  firebase_core: "0.5.0"
  firebase_auth: ^0.18.0
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.0
  firebase_analytics: ^6.0.0
  path_provider: ^1.6.7
  connectivity: ^0.4.9+3
  argon_buttons_flutter: ^1.0.6
  flutter_native_image: ^0.0.5
  rounded_loading_button: ^1.0.13
  expansion_card: ^0.1.0
  firebase_ml_vision: ^0.9.9
  sleek_circular_slider: ^1.2.0+web
  widget_circular_animator: ^0.1.5+1
  flare_flutter: ^2.0.6
  flutter_markdown: ^0.5.2
  timeago: ^2.0.29
  pdf: ^2.0.0
  printing: ^4.0.0
  markdown: ^3.0.0
  reorderables: ^0.3.2
  showcaseview: ^0.1.6
  flutter_typeahead: ^2.0.0
  settings_ui: ^0.6.0
  intro_slider: ^2.3.4
  package_info: ^2.0.0
  url_launcher: ^6.0.2
  share: ^2.0.0
  image_gallery_saver: ^1.6.8
  flutter_inapp_purchase: ^4.0.0
  confetti: ^0.5.5
  feature_discovery: ^0.13.0
  animated_text_kit: ^4.2.1
  hive: ^1.4.0
  flutter_local_notifications: ^4.0.1+2
  charts_flutter: ^0.10.0
  fl_chart: ^0.36.2
  auto_size_text: ^2.1.0
  qr_code_scanner: ^0.4.0
 
  simple_edge_detection:
    path: packages/flutter-simple-edge-detection
  wave:
    path: packages/wave
  flushbar:
    path: packages/flushbar
  bezier_chart:
    path: packages/bezier-chart
  upgrader:
    path: packages/upgrader


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  flutter_native_splash: ^0.2.0
  hive_generator: ^0.8.0
  build_runner: ^1.8.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon_w_bg.png"

flutter_native_splash:
  color: "#3b4252"
  image: assets/icons/icon_w_bg.png
  android: true
  ios: false
  web: false
  fullscreen: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flare/
    - assets/illustrations/
    - assets/icons/
    - assets/crypto/addresses/
    - assets/crypto/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TRT
      fonts:
        - asset: assets/fonts/trt_bold.otf
        - asset: assets/fonts/trt_bold_italic.otf
        - asset: assets/fonts/trt_light.otf
        - asset: assets/fonts/trt_light_italic.otf
        - asset: assets/fonts/trt_medium.otf
        - asset: assets/fonts/trt_medium_italic.otf
        - asset: assets/fonts/trt_regular.otf
        - asset: assets/fonts/trt_regular_italic.otf
        
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
